apiVersion: v2
name: prometheuschart
description: A Helm chart for Prometheus only
version: 0.1.0
appVersion: "2.45.0"
dependencies:
  - name: prometheus
    version: 25.18.0
    repository: https://prometheus-community.github.io/helm-charts