prometheus:
  prometheusSpec:
    alertmanager:
      enabled: false
    storageSpec:
      volumeClaimTemplate:
        metadata:
          name: prometheus-data
        spec:
          accessModes: ["ReadWriteOnce"]
          storageClassName: local-storage
          resources:
            requests:
              storage: 6Gi
    tolerations:
      - key: node-role.kubernetes.io/control-plane
        operator: Exists
        effect: NoSchedule
    resources:
      limits:
        memory: 2Gi
        cpu: 1
      requests:
        memory: 1Gi
        cpu: 500m
    readinessProbe:
      initialDelaySeconds: 30
      timeoutSeconds: 5
    livenessProbe:
      initialDelaySeconds: 30
      timeoutSeconds: 5
