# Hérite des valeurs du chart kube-prometheus-stack
kube-prometheus-stack:
  prometheus:
    ingress:
      enabled: false
  grafana:
    enabled: false

metallb:
  enabled: true
  ipRange: "10.0.1.242-10.0.1.250"

ingress:
  enabled: true
  host: "prometheus-kubequest.duckdns.org"
  annotations:
    nginx.ingress.kubernetes.io/backend-protocol: "HTTP"