prometheus:
  server:
    enabled: true
    ingress:
      enabled: true
      hosts:
        - prometheus-kubequest.duckdns.org
      annotations:
        nginx.ingress.kubernetes.io/backend-protocol: "HTTP"

  alertmanager:
    enabled: false

  pushgateway:
    enabled: false

  nodeExporter:
    enabled: false

  serviceAccounts:
    server:
      create: true
