kube-prometheus-stack:
  grafana:
    adminPassword: admin
    service:
      type: NodePort
    ingress:
      enabled: true
      hosts:
        - grafana.local.tcloud
  prometheus:
    service:
      type: NodePort
  alertmanager:
    enabled: false
