apiVersion: v1
kind: Secret
metadata:
  name: secret-mysql
  namespace: default
type: Opaque
stringData:
  mysql-root-password: "kubequest123"
  mysql-password: "kubequest123"
  mysql-replication-password: "kubequest123"

  