apiVersion: batch/v1
kind: Job
metadata:
  name: prometheus-storage-prepare
  namespace: monitoring
spec:
  template:
    spec:
      nodeSelector:
        kubernetes.io/hostname: k8s-server
      tolerations:
        - key: node-role.kubernetes.io/control-plane
          operator: Exists
          effect: NoSchedule
      containers:
        - name: storage-prepare
          image: busybox:1.35
          command:
            - /bin/sh
            - -c
            - |
              mkdir -p /mnt/prometheus
              chmod 755 /mnt/prometheus
              chown 65534:65534 /mnt/prometheus
              echo "Storage directory prepared successfully"
          volumeMounts:
            - name: prometheus-storage
              mountPath: /mnt/prometheus
      volumes:
        - name: prometheus-storage
          hostPath:
            path: /mnt/prometheus
            type: DirectoryOrCreate
      restartPolicy: Never
  backoffLimit: 3 