apiVersion: v1
kind: List
items:
  - apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: prometheus-kube-prometheus-operator
      namespace: monitoring
      labels:
        app: kube-prometheus-stack-operator
        app.kubernetes.io/component: prometheus-operator
        app.kubernetes.io/instance: prometheus
        app.kubernetes.io/name: kube-prometheus-stack-prometheus-operator
        app.kubernetes.io/part-of: kube-prometheus-stack
        app.kubernetes.io/managed-by: Helm
    spec:
      replicas: 1
      selector:
        matchLabels:
          app: kube-prometheus-stack-operator
          release: prometheus
      template:
        metadata:
          labels:
            app: kube-prometheus-stack-operator
            app.kubernetes.io/component: prometheus-operator
            app.kubernetes.io/instance: prometheus
            app.kubernetes.io/name: kube-prometheus-stack-prometheus-operator
            app.kubernetes.io/part-of: kube-prometheus-stack
        spec:
          serviceAccountName: prometheus-kube-prometheus-operator
          containers:
            - name: kube-prometheus-stack
              image: quay.io/prometheus-operator/prometheus-operator:v0.83.0
              args:
                - --kubelet-service=kube-system/prometheus-kube-prometheus-kubelet
                - --kubelet-endpoints=true
                - --kubelet-endpointslice=false
                - --localhost=127.0.0.1
                - --prometheus-config-reloader=quay.io/prometheus-operator/prometheus-config-reloader:v0.83.0
                - --config-reloader-cpu-request=0
                - --config-reloader-cpu-limit=0
                - --config-reloader-memory-request=0
                - --config-reloader-memory-limit=0
                - --thanos-default-base-image=quay.io/thanos/thanos:v0.38.0
                - --secret-field-selector=type!=kubernetes.io/dockercfg,type!=kubernetes.io/service-account-token,type!=helm.sh/release.v1
                - --web.enable-tls=true
                - --web.cert-file=/cert/cert
                - --web.key-file=/cert/key
                - --web.listen-address=:10250
                - --web.tls-min-version=VersionTLS13
              ports:
                - containerPort: 10250
                  name: https
              volumeMounts:
                - name: tls-secret
                  mountPath: /cert
                  readOnly: true
              livenessProbe:
                httpGet:
                  path: /healthz
                  port: https
                  scheme: HTTPS
              readinessProbe:
                httpGet:
                  path: /healthz
                  port: https
                  scheme: HTTPS
          volumes:
            - name: tls-secret
              secret:
                secretName: prometheus-kube-prometheus-admission
