apiVersion: v1
kind: Secret
metadata:
  name: prometheus-grafana
  namespace: monitoring
  labels:
    app.kubernetes.io/name: grafana
    app.kubernetes.io/instance: prometheus
type: Opaque
stringData:
  admin-user: admin
  admin-password: prom-operator
