apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: prometheus-local-storage
  annotations:
    storageclass.kubernetes.io/is-default-class: "false"
provisioner: kubernetes.io/no-provisioner
volumeBindingMode: WaitForFirstConsumer
reclaimPolicy: Retain 