apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mysql-db
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  project: default
  source:
    repoURL: https://github.com/simlf/KubeQuest.git
    targetRevision: feat-app-chart
    path: mysqlchart
  destination:
    name: in-cluster
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
