apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prometheus
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  project: default
  source:
    repoURL: https://github.com/simlf/KubeQuest.git
    targetRevision: feat/logging-system-refactoring
    path: prometheuschart
  destination:
    name: in-cluster
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    repoURL: https://prometheus-community.github.io/helm-charts
    targetRevision: "23.3.0"
    chart: prometheus
    helm:
      releaseName: prometheus
      values: |
        prometheus:
          prometheusSpec:
            serviceMonitorSelectorNilUsesHelmValues: false
            serviceMonitorSelector: {}
            serviceMonitorNamespaceSelector: {}
            podMonitorSelectorNilUsesHelmValues: false
            podMonitorSelector: {}
            podMonitorNamespaceSelector: {}
            ruleSelectorNilUsesHelmValues: false
            ruleSelector: {}
            ruleNamespaceSelector: {}
            probeSelectorNilUsesHelmValues: false
            probeSelector: {}
            probeNamespaceSelector: {}
            scrapeConfigSelectorNilUsesHelmValues: false
            scrapeConfigSelector: {}
            scrapeConfigNamespaceSelector: {}
  destination:
    name: in-cluster
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true 