replicaCount: 1

image:
  repository: cley44/kubequest
  tag: "1.2"
  pullPolicy: IfNotPresent

# Health Probes configuration
healthProbes:
  enabled: true
  # Startup Probe - vérifie que l'app a démarré (important pour les apps lentes à démarrer)
  startup:
    enabled: true
    httpGet:
      path: /health/startup
      port: 80
      scheme: HTTP
    initialDelaySeconds: 5
    periodSeconds: 5
    timeoutSeconds: 3
    failureThreshold: 30  # 30 * 5 = 150 secondes max pour le démarrage
    successThreshold: 1
  
  # Readiness Probe - vérifie que l'app est prête à recevoir du trafic
  readiness:
    enabled: true
    httpGet:
      path: /health/ready
      port: 80
      scheme: HTTP
    initialDelaySeconds: 5
    periodSeconds: 10
    timeoutSeconds: 3
    failureThreshold: 3
    successThreshold: 1
  
  # Liveness Probe - vérifie que l'app fonctionne correctement
  liveness:
    enabled: true
    httpGet:
      path: /health/live
      port: 80
      scheme: HTTP
    initialDelaySeconds: 30
    periodSeconds: 30
    timeoutSeconds: 5
    failureThreshold: 3
    successThreshold: 1

service:
  type: ClusterIP
  port: 443

envSecretName: secret-mysql

secret:
  enabled: true
  name: app-env-secret
  data:
    DB_HOST: mysql-db.default.svc.cluster.local
    DB_DATABASE: kubequest
    APP_KEY: qqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqq
    APP_DEBUG: "true"
    APP_ENV: local

ingress:
  enabled: true
  className: nginx
  hosts:
    - host: kubequest.duckdns.org
      paths:
        - path: /
          pathType: Prefix
  tls:
    - secretName: app-tls
      hosts:
        - kubequest.duckdns.org
