replicaCount: 1

image:
  repository: cley44/kubequest
  tag: "1.2"
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 80

envSecretName: app-env-secret

secret:
  enabled: true
  name: app-env-secret
  data:
    APP_KEY: qqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqq

ingress:
  enabled: true
  className: nginx
  hosts:
    - host: app.example.com
      paths:
        - path: /
          pathType: Prefix
