apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-data-claim
  namespace: default
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 8Gi
  storageClassName: local-storage
  volumeName: mysql-pv  # Direct reference to our existing PV 