apiVersion: v2
name: grafanachart
description: A Helm chart for Grafana visualization
type: application
version: 0.1.0
appVersion: "10.2.0"
dependencies:
  - name: grafana
    version: "7.0.0"
    repository: https://grafana.github.io/helm-charts 