# - name: Install nginx controller
#   shell: wget -P /home/adminuser https://raw.githubusercontent.com/kubernetes/ingress-nginx/controller-v1.12.1/deploy/static/provider/cloud/deploy.yaml

# - name: Add hostNetwork
#   shell: |
#     awk '
#      /^kind: Deployment$/ {in_deployment=1}
#      /^kind: / && !/^kind: Deployment$/ {in_deployment=0}
#      in_deployment && /^\s*spec:\s*$/ {spec=1}
#      spec && /^\s*template:\s*$/ {template=1}
#      /^\s*spec:\s*$/ && template {print; print "      hostNetwork: true"; template=0; spec=0; next}
#      {print}
#      ' /home/adminuser/deploy.yaml > /home/adminuser/tmp1.yaml

# - name: Add hostPort
#   shell: |
#     awk '
#     /containerPort: 443/ {print; print "          hostPort: 443"; next}
#     {print}
#     ' /home/adminuser/tmp1.yaml > /home/adminuser/tmp2.yaml

# - name: Rename tmp2.yaml
#   shell: mv /home/adminuser/tmp2.yaml /home/adminuser/deploy.yaml

# - name: remove tmp.yaml
#   shell: rm -f /home/adminuser/tmp*

- name: Copy nginx controller manifest
  copy:
    src: deploy.yaml
    dest: /home/adminuser/deploy.yaml
    owner: root
    group: root
    mode: "0644"

- name: Apply nginx controller
  shell: kubectl apply -f /home/adminuser/deploy.yaml

- name: Wait for nginx controller to be up
  shell: kubectl wait pod --selector=app.kubernetes.io/component=controller --for=condition=Ready --namespace=ingress-nginx --timeout=60s
