- name: Copy nginx controller manifest
  copy:
    src: deploy.yaml
    dest: /home/adminuser/deploy.yaml
    owner: root
    group: root
    mode: "0644"

- name: Apply nginx controller
  shell: kubectl apply -f /home/adminuser/deploy.yaml

- name: Wait for nginx controller to be up
  shell: kubectl wait pod --selector=app.kubernetes.io/component=controller --for=condition=Ready --namespace=ingress-nginx --timeout=60s
