apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: loki
  namespace: monitoring
  labels:
    release: kube-prometheus-stack
spec:
  selector:
    matchLabels:
      app: loki
      release: loki
  endpoints:
    - interval: 15s
      path: /metrics
      port: http-metrics
