apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "appchart.fullname" . }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "appchart.name" . }}
  template:
    metadata:
      labels:
        app: {{ include "appchart.name" . }}
    spec:
      containers:
        - name: php
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 80
          envFrom:
            - secretRef:
                name: {{ .Values.envSecretName }}
            - secretRef:
                name: {{ .Values.secret.name }}
      livenessProbe:
        httpGet:
          path: /
          port: 80
        initialDelaySeconds: 30
        periodSeconds: 10
        timeoutSeconds: 3
      readinessProbe:
        httpGet:
          path: /
          port: 80
        initialDelaySeconds: 30
        periodSeconds: 10
        timeoutSeconds: 3